package com.example.demo.entities;
// Generated 18:43:28, 30 thg 12, 2025 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.springframework.format.annotation.DateTimeFormat;

import com.example.demo.enums.StatusAccount;
import com.fasterxml.jackson.annotation.JsonFormat;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name = "account", uniqueConstraints = { @UniqueConstraint(columnNames = "email"),
		@UniqueConstraint(columnNames = "username") })
public class Account implements java.io.Serializable {

	private Integer id;
	private String fullName;
	private String email;
	private String username;
	private String password;
	private String phone;
	private String address;
	
	@Temporal(TemporalType.DATE)
	@JsonFormat(pattern = "dd/MM/yyyy")
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date dob;
	private String avatar;
	private Date createdAt;
	private Date updatedAt;
	private StatusAccount status;
	private Set<PromotionAccount> promotionAccounts = new HashSet<PromotionAccount>(0);
	private Set<Message> messages = new HashSet<Message>(0);
	private Set<Notification> notifications = new HashSet<Notification>(0);
	private Set<Orders> orders = new HashSet<Orders>(0);
	private Set<Payment> payments = new HashSet<Payment>(0);
	private Set<RoleAccount> roleAccounts = new HashSet<RoleAccount>(0);
	private Set<ShipperProfile> shipperProfiles = new HashSet<ShipperProfile>(0);
	private Set<SellerReview> sellerReviews = new HashSet<SellerReview>(0);
	private Set<ProductReview> productReviews = new HashSet<ProductReview>(0);
	private Set<SellerProfile> sellerProfiles = new HashSet<SellerProfile>(0);
	private Set<Cart> carts = new HashSet<Cart>(0);
	private Set<ChatParticipant> chatParticipants = new HashSet<ChatParticipant>(0);
	private Set<ShipperReview> shipperReviews = new HashSet<ShipperReview>(0);

	public Account() {
	}

	public Account(String fullName, String email, String username, String password, String phone, String address,
			Date dob, String avatar, Date createdAt, Date updatedAt, StatusAccount status) {
		this.fullName = fullName;
		this.email = email;
		this.username = username;
		this.password = password;
		this.phone = phone;
		this.address = address;
		this.dob = dob;
		this.avatar = avatar;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.status = status;
	}

	public Account(String fullName, String email, String username, String password, String phone, String address,
			Date dob, String avatar, Date createdAt, Date updatedAt, StatusAccount status,
			Set<PromotionAccount> promotionAccounts, Set<Message> messages, Set<Notification> notifications,
			Set<Orders> orders, Set<Payment> payments, Set<RoleAccount> roleAccounts,
			Set<ShipperProfile> shipperProfiles, Set<SellerReview> sellerReviews, Set<ProductReview> productReviews,
			Set<SellerProfile> sellerProfiles, Set<Cart> carts, Set<ChatParticipant> chatParticipants,
			Set<ShipperReview> shipperReviews) {
		this.fullName = fullName;
		this.email = email;
		this.username = username;
		this.password = password;
		this.phone = phone;
		this.address = address;
		this.dob = dob;
		this.avatar = avatar;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.promotionAccounts = promotionAccounts;
		this.messages = messages;
		this.notifications = notifications;
		this.orders = orders;
		this.payments = payments;
		this.roleAccounts = roleAccounts;
		this.shipperProfiles = shipperProfiles;
		this.sellerReviews = sellerReviews;
		this.productReviews = productReviews;
		this.sellerProfiles = sellerProfiles;
		this.carts = carts;
		this.chatParticipants = chatParticipants;
		this.shipperReviews = shipperReviews;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "full_name", nullable = false, length = 250)
	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	@Column(name = "email", unique = true, nullable = false, length = 250)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "username", unique = true, nullable = false, length = 250)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 250)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "phone", nullable = false, length = 250)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "address", nullable = false, length = 500)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dob", nullable = false, length = 10)
	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	@Column(name = "avatar", nullable = false, length = 250)
	public String getAvatar() {
		return this.avatar;
	}

	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_at", nullable = false, length = 10)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "updated_at", nullable = false, length = 10)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<PromotionAccount> getPromotionAccounts() {
		return this.promotionAccounts;
	}

	public void setPromotionAccounts(Set<PromotionAccount> promotionAccounts) {
		this.promotionAccounts = promotionAccounts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<Message> getMessages() {
		return this.messages;
	}

	public void setMessages(Set<Message> messages) {
		this.messages = messages;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<Notification> getNotifications() {
		return this.notifications;
	}

	public void setNotifications(Set<Notification> notifications) {
		this.notifications = notifications;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<Orders> getOrders() {
		return this.orders;
	}

	public void setOrders(Set<Orders> orders) {
		this.orders = orders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<Payment> getPayments() {
		return this.payments;
	}

	public void setPayments(Set<Payment> payments) {
		this.payments = payments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<RoleAccount> getRoleAccounts() {
		return this.roleAccounts;
	}

	public void setRoleAccounts(Set<RoleAccount> roleAccounts) {
		this.roleAccounts = roleAccounts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<ShipperProfile> getShipperProfiles() {
		return this.shipperProfiles;
	}

	public void setShipperProfiles(Set<ShipperProfile> shipperProfiles) {
		this.shipperProfiles = shipperProfiles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<SellerReview> getSellerReviews() {
		return this.sellerReviews;
	}

	public void setSellerReviews(Set<SellerReview> sellerReviews) {
		this.sellerReviews = sellerReviews;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<ProductReview> getProductReviews() {
		return this.productReviews;
	}

	public void setProductReviews(Set<ProductReview> productReviews) {
		this.productReviews = productReviews;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<SellerProfile> getSellerProfiles() {
		return this.sellerProfiles;
	}

	public void setSellerProfiles(Set<SellerProfile> sellerProfiles) {
		this.sellerProfiles = sellerProfiles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<Cart> getCarts() {
		return this.carts;
	}

	public void setCarts(Set<Cart> carts) {
		this.carts = carts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<ChatParticipant> getChatParticipants() {
		return this.chatParticipants;
	}

	public void setChatParticipants(Set<ChatParticipant> chatParticipants) {
		this.chatParticipants = chatParticipants;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<ShipperReview> getShipperReviews() {
		return this.shipperReviews;
	}

	public void setShipperReviews(Set<ShipperReview> shipperReviews) {
		this.shipperReviews = shipperReviews;
	}

	@Enumerated(EnumType.STRING)
	@Column(name = "status", nullable = false, length = 250)
	public StatusAccount getStatus() {
		return status;
	}

	public void setStatus(StatusAccount status) {
		this.status = status;
	}

}
