package com.example.demo.entities;
// Generated 18:43:28, 30 thg 12, 2025 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Chat generated by hbm2java
 */
@Entity
@Table(name = "chat")
public class Chat implements java.io.Serializable {

	private Integer id;
	private Date createdAt;
	private String statusChat;
	private Set<Message> messages = new HashSet<Message>(0);
	private Set<ChatParticipant> chatParticipants = new HashSet<ChatParticipant>(0);

	public Chat() {
	}

	public Chat(Date createdAt, String statusChat) {
		this.createdAt = createdAt;
		this.statusChat = statusChat;
	}

	public Chat(Date createdAt, String statusChat, Set<Message> messages, Set<ChatParticipant> chatParticipants) {
		this.createdAt = createdAt;
		this.statusChat = statusChat;
		this.messages = messages;
		this.chatParticipants = chatParticipants;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "status_chat", nullable = false, length = 250)
	public String getStatusChat() {
		return this.statusChat;
	}

	public void setStatusChat(String statusChat) {
		this.statusChat = statusChat;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chat")
	public Set<Message> getMessages() {
		return this.messages;
	}

	public void setMessages(Set<Message> messages) {
		this.messages = messages;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chat")
	public Set<ChatParticipant> getChatParticipants() {
		return this.chatParticipants;
	}

	public void setChatParticipants(Set<ChatParticipant> chatParticipants) {
		this.chatParticipants = chatParticipants;
	}

}
