package com.example.demo.entities;
// Generated 18:43:28, 30 thg 12, 2025 by Hibernate Tools 4.3.6.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * ChatParticipant generated by hbm2java
 */
@Entity
@Table(name = "chat_participant", uniqueConstraints = @UniqueConstraint(columnNames = { "chat_id", "account_id" }))
public class ChatParticipant implements java.io.Serializable {

	private Integer id;
	private Account account;
	private Chat chat;
	private Message message;
	private String roleInParticipant;

	public ChatParticipant() {
	}

	public ChatParticipant(Account account, Chat chat, Message message, String roleInParticipant) {
		this.account = account;
		this.chat = chat;
		this.message = message;
		this.roleInParticipant = roleInParticipant;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account_id", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "chat_id", nullable = false)
	public Chat getChat() {
		return this.chat;
	}

	public void setChat(Chat chat) {
		this.chat = chat;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "last_read_message_id", nullable = false)
	public Message getMessage() {
		return this.message;
	}

	public void setMessage(Message message) {
		this.message = message;
	}

	@Column(name = "role_in_participant", nullable = false, length = 8)
	public String getRoleInParticipant() {
		return this.roleInParticipant;
	}

	public void setRoleInParticipant(String roleInParticipant) {
		this.roleInParticipant = roleInParticipant;
	}

}
