package com.example.demo.entities;
// Generated 18:43:28, 30 thg 12, 2025 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Message generated by hbm2java
 */
@Entity
@Table(name = "message")
public class Message implements java.io.Serializable {

	private Integer id;
	private Account account;
	private Chat chat;
	private String content;
	private String type;
	private Date createdAt;
	private String attachmentPhoto;
	private boolean isDeleted;
	private Set<ChatParticipant> chatParticipants = new HashSet<ChatParticipant>(0);

	public Message() {
	}

	public Message(Account account, Chat chat, String content, String type, Date createdAt, boolean isDeleted) {
		this.account = account;
		this.chat = chat;
		this.content = content;
		this.type = type;
		this.createdAt = createdAt;
		this.isDeleted = isDeleted;
	}

	public Message(Account account, Chat chat, String content, String type, Date createdAt, String attachmentPhoto,
			boolean isDeleted, Set<ChatParticipant> chatParticipants) {
		this.account = account;
		this.chat = chat;
		this.content = content;
		this.type = type;
		this.createdAt = createdAt;
		this.attachmentPhoto = attachmentPhoto;
		this.isDeleted = isDeleted;
		this.chatParticipants = chatParticipants;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sender_account_id", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "chat_id", nullable = false)
	public Chat getChat() {
		return this.chat;
	}

	public void setChat(Chat chat) {
		this.chat = chat;
	}

	@Column(name = "content", nullable = false, length = 1000)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "type", nullable = false, length = 6)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "attachment_photo", length = 250)
	public String getAttachmentPhoto() {
		return this.attachmentPhoto;
	}

	public void setAttachmentPhoto(String attachmentPhoto) {
		this.attachmentPhoto = attachmentPhoto;
	}

	@Column(name = "is_deleted", nullable = false)
	public boolean isIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "message")
	public Set<ChatParticipant> getChatParticipants() {
		return this.chatParticipants;
	}

	public void setChatParticipants(Set<ChatParticipant> chatParticipants) {
		this.chatParticipants = chatParticipants;
	}

}
