package com.example.demo.entities;
// Generated 18:43:28, 30 thg 12, 2025 by Hibernate Tools 4.3.6.Final

import java.util.Date;

import com.example.demo.enums.NotificationType;
import com.example.demo.enums.ReceiverType;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Notification generated by hbm2java
 */
@Entity
@Table(name = "notification")
public class Notification implements java.io.Serializable {

	private Integer id;
	private Account account;
	private Category category;
	private Orders order;
	private Product product;
	private Promotion promotion;
	private ReceiverType receiverType;
	private NotificationType typeNotification;
	private String titleNotification;
	private String messageNotification;
	private boolean isRead;
	private Date createdAt;

	public Notification() {
	}

	public Notification(ReceiverType receiverType, NotificationType typeNotification, String titleNotification,
			String messageNotification, boolean isRead, Date createdAt) {
		this.receiverType = receiverType;
		this.typeNotification = typeNotification;
		this.titleNotification = titleNotification;
		this.messageNotification = messageNotification;
		this.isRead = isRead;
		this.createdAt = createdAt;
	}

	public Notification(Account account, Category category, Orders order, Product product, Promotion promotion,
			ReceiverType receiverType, NotificationType typeNotification, String titleNotification, String messageNotification,
			boolean isRead, Date createdAt) {
		this.account = account;
		this.category = category;
		this.order = order;
		this.product = product;
		this.promotion = promotion;
		this.receiverType = receiverType;
		this.typeNotification = typeNotification;
		this.titleNotification = titleNotification;
		this.messageNotification = messageNotification;
		this.isRead = isRead;
		this.createdAt = createdAt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account_id")
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id")
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_id")
	public Orders getOrder() {
		return this.order;
	}

	public void setOrder(Orders order) {
		this.order = order;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id")
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "promotion_id")
	public Promotion getPromotion() {
		return this.promotion;
	}

	public void setPromotion(Promotion promotion) {
		this.promotion = promotion;
	}

	@Enumerated(EnumType.STRING)
	@Column(name = "receiver_type", nullable = false, length = 8)
	public ReceiverType getReceiverType() {
		return this.receiverType;
	}

	public void setReceiverType(ReceiverType receiverType) {
		this.receiverType = receiverType;
	}
	
	@Enumerated(EnumType.STRING)
	@Column(name = "type_notification", nullable = false, length = 9)
	public NotificationType getTypeNotification() {
		return this.typeNotification;
	}

	public void setTypeNotification(NotificationType typeNotification) {
		this.typeNotification = typeNotification;
	}

	@Column(name = "title_notification", nullable = false, length = 250)
	public String getTitleNotification() {
		return this.titleNotification;
	}

	public void setTitleNotification(String titleNotification) {
		this.titleNotification = titleNotification;
	}

	@Column(name = "message_notification", nullable = false, length = 800)
	public String getMessageNotification() {
		return this.messageNotification;
	}

	public void setMessageNotification(String messageNotification) {
		this.messageNotification = messageNotification;
	}

	@Column(name = "is_read", nullable = false)
	public boolean isIsRead() {
		return this.isRead;
	}

	public void setIsRead(boolean isRead) {
		this.isRead = isRead;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

}
