package com.example.demo.entities;
// Generated 18:43:28, 30 thg 12, 2025 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.example.demo.enums.OrderStatus;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name = "orders", uniqueConstraints = @UniqueConstraint(columnNames = "order_code"))
public class Orders implements java.io.Serializable {

	private Integer id;
	private Account account;
	private PaymentMethod paymentMethod;
	private String orderCode;
	private float totalAmount;
	private float discountAmount;
	private int finalAmount;
	private OrderStatus statusOrder;
	private String shippingAddress;
	private Date createdAt;
	private Date updatedAt;
	private Set<Notification> notifications = new HashSet<Notification>(0);
	private Set<OrderItem> orderItems = new HashSet<OrderItem>(0);
	private Set<Payment> payments = new HashSet<Payment>(0);

	public Orders() {
	}

	public Orders(Account account, PaymentMethod paymentMethod, String orderCode, float totalAmount,
			float discountAmount, int finalAmount, OrderStatus statusOrder, String shippingAddress, Date createdAt,
			Date updatedAt) {
		this.account = account;
		this.paymentMethod = paymentMethod;
		this.orderCode = orderCode;
		this.totalAmount = totalAmount;
		this.discountAmount = discountAmount;
		this.finalAmount = finalAmount;
		this.statusOrder = statusOrder;
		this.shippingAddress = shippingAddress;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Orders(Account account, PaymentMethod paymentMethod, String orderCode, float totalAmount,
			float discountAmount, int finalAmount, OrderStatus statusOrder, String shippingAddress, Date createdAt,
			Date updatedAt, Set<Notification> notifications, Set<OrderItem> orderItems, Set<Payment> payments) {
		this.account = account;
		this.paymentMethod = paymentMethod;
		this.orderCode = orderCode;
		this.totalAmount = totalAmount;
		this.discountAmount = discountAmount;
		this.finalAmount = finalAmount;
		this.statusOrder = statusOrder;
		this.shippingAddress = shippingAddress;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.notifications = notifications;
		this.orderItems = orderItems;
		this.payments = payments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account_id", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "payment_method_id", nullable = false)
	public PaymentMethod getPaymentMethod() {
		return this.paymentMethod;
	}

	public void setPaymentMethod(PaymentMethod paymentMethod) {
		this.paymentMethod = paymentMethod;
	}

	@Column(name = "order_code", unique = true, nullable = false, length = 250)
	public String getOrderCode() {
		return this.orderCode;
	}

	public void setOrderCode(String orderCode) {
		this.orderCode = orderCode;
	}

	@Column(name = "total_amount", nullable = false, precision = 12, scale = 0)
	public float getTotalAmount() {
		return this.totalAmount;
	}

	public void setTotalAmount(float totalAmount) {
		this.totalAmount = totalAmount;
	}

	@Column(name = "discount_amount", nullable = false, precision = 12, scale = 0)
	public float getDiscountAmount() {
		return this.discountAmount;
	}

	public void setDiscountAmount(float discountAmount) {
		this.discountAmount = discountAmount;
	}

	@Column(name = "final_amount", nullable = false)
	public int getFinalAmount() {
		return this.finalAmount;
	}

	public void setFinalAmount(int finalAmount) {
		this.finalAmount = finalAmount;
	}

	@Enumerated(EnumType.STRING)
	@Column(name = "status_order", nullable = false, length = 250)
	public OrderStatus getStatusOrder() {
		return this.statusOrder;
	}

	public void setStatusOrder(OrderStatus statusOrder) {
		this.statusOrder = statusOrder;
	}

	@Column(name = "shipping_address", nullable = false, length = 500)
	public String getShippingAddress() {
		return this.shippingAddress;
	}

	public void setShippingAddress(String shippingAddress) {
		this.shippingAddress = shippingAddress;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_at", nullable = false, length = 10)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "updated_at", nullable = false, length = 10)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "order")
	public Set<Notification> getNotifications() {
		return this.notifications;
	}

	public void setNotifications(Set<Notification> notifications) {
		this.notifications = notifications;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "order")
	public Set<OrderItem> getOrderItems() {
		return this.orderItems;
	}

	public void setOrderItems(Set<OrderItem> orderItems) {
		this.orderItems = orderItems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "order")
	public Set<Payment> getPayments() {
		return this.payments;
	}

	public void setPayments(Set<Payment> payments) {
		this.payments = payments;
	}

}
