package com.example.demo.entities;
// Generated 18:43:28, 30 thg 12, 2025 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * PaymentMethod generated by hbm2java
 */
@Entity
@Table(name = "payment_method")
public class PaymentMethod implements java.io.Serializable {

	private Integer id;
	private String paymentCode;
	private String paymentName;
	private String paymentDescription;
	private String paymentStatus;
	private Date createdAt;
	private Date updatedAt;
	private Set<Orders> orders = new HashSet<Orders>(0);
	private Set<Payment> payments = new HashSet<Payment>(0);

	public PaymentMethod() {
	}

	public PaymentMethod(String paymentCode, String paymentName, String paymentDescription, String paymentStatus,
			Date createdAt, Date updatedAt) {
		this.paymentCode = paymentCode;
		this.paymentName = paymentName;
		this.paymentDescription = paymentDescription;
		this.paymentStatus = paymentStatus;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public PaymentMethod(String paymentCode, String paymentName, String paymentDescription, String paymentStatus,
			Date createdAt, Date updatedAt, Set<Orders> orders, Set<Payment> payments) {
		this.paymentCode = paymentCode;
		this.paymentName = paymentName;
		this.paymentDescription = paymentDescription;
		this.paymentStatus = paymentStatus;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.orders = orders;
		this.payments = payments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "payment_code", nullable = false, length = 250)
	public String getPaymentCode() {
		return this.paymentCode;
	}

	public void setPaymentCode(String paymentCode) {
		this.paymentCode = paymentCode;
	}

	@Column(name = "payment_name", nullable = false, length = 250)
	public String getPaymentName() {
		return this.paymentName;
	}

	public void setPaymentName(String paymentName) {
		this.paymentName = paymentName;
	}

	@Column(name = "payment_description", nullable = false, length = 250)
	public String getPaymentDescription() {
		return this.paymentDescription;
	}

	public void setPaymentDescription(String paymentDescription) {
		this.paymentDescription = paymentDescription;
	}

	@Column(name = "payment_status", nullable = false, length = 250)
	public String getPaymentStatus() {
		return this.paymentStatus;
	}

	public void setPaymentStatus(String paymentStatus) {
		this.paymentStatus = paymentStatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_at", nullable = false, length = 10)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "updated_at", nullable = false, length = 10)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "paymentMethod")
	public Set<Orders> getOrders() {
		return this.orders;
	}

	public void setOrders(Set<Orders> orders) {
		this.orders = orders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "paymentMethod")
	public Set<Payment> getPayments() {
		return this.payments;
	}

	public void setPayments(Set<Payment> payments) {
		this.payments = payments;
	}

}
