package com.example.demo.entities;
// Generated 18:43:28, 30 thg 12, 2025 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.example.demo.enums.ProductStatus;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product")
public class Product implements java.io.Serializable {

	private Integer id;
	private Category category;
	private SellerProfile sellerProfile;
	private String nameProduct;
	private String description;
	private float price;
	private int stockQuantity;
	private String photo;
	private float discountPrice;
	private String sku;
	private ProductStatus status;
	private Float weight;
	private Float dimensions;
	private Boolean isFeatured;
	private Boolean isNew;
	private Date createdAt;
	private Date updatedAt;
	private int reviewCount;
	private float avgRating;
	private Set<OrderItem> orderItems = new HashSet<OrderItem>(0);
	private Set<Cart> carts = new HashSet<Cart>(0);
	private Set<Notification> notifications = new HashSet<Notification>(0);
	private Set<ProductImages> productImageses = new HashSet<ProductImages>(0);
	private Set<PromotionProduct> promotionProducts = new HashSet<PromotionProduct>(0);
	private Set<ProductReview> productReviews = new HashSet<ProductReview>(0);

	public Product() {
	}

	public int getReviewCount() {
		return reviewCount;
	}

	public void setReviewCount(int reviewCount) {
		this.reviewCount = reviewCount;
	}

	public float getAvgRating() {
		return avgRating;
	}

	public void setAvgRating(float avgRating) {
		this.avgRating = avgRating;
	}

	public Product(Category category, SellerProfile sellerProfile, String nameProduct, String description, float price,
			int stockQuantity, String photo, float discountPrice, String sku, Date createdAt, Date updatedAt,
			int reviewCount, float avgRating) {
		this.category = category;
		this.sellerProfile = sellerProfile;
		this.nameProduct = nameProduct;
		this.description = description;
		this.price = price;
		this.stockQuantity = stockQuantity;
		this.photo = photo;
		this.discountPrice = discountPrice;
		this.sku = sku;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.reviewCount = reviewCount;
		this.avgRating = avgRating;
	}

	public Product(Category category, SellerProfile sellerProfile, String nameProduct, String description, float price,
			int stockQuantity, String photo, float discountPrice, String sku, ProductStatus status, Float weight,
			Float dimensions, Boolean isFeatured, Boolean isNew, Date createdAt, Date updatedAt, int reviewCount,
			float avgRating, Set<OrderItem> orderItems, Set<Cart> carts, Set<Notification> notifications,
			Set<ProductImages> productImageses, Set<PromotionProduct> promotionProducts,
			Set<ProductReview> productReviews) {
		this.category = category;
		this.sellerProfile = sellerProfile;
		this.nameProduct = nameProduct;
		this.description = description;
		this.price = price;
		this.stockQuantity = stockQuantity;
		this.photo = photo;
		this.discountPrice = discountPrice;
		this.sku = sku;
		this.status = status;
		this.weight = weight;
		this.dimensions = dimensions;
		this.isFeatured = isFeatured;
		this.isNew = isNew;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.orderItems = orderItems;
		this.carts = carts;
		this.notifications = notifications;
		this.productImageses = productImageses;
		this.promotionProducts = promotionProducts;
		this.productReviews = productReviews;
		this.reviewCount = reviewCount;
		this.avgRating = avgRating;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id", nullable = false)
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "seller_id", nullable = false)
	public SellerProfile getSellerProfile() {
		return this.sellerProfile;
	}

	public void setSellerProfile(SellerProfile sellerProfile) {
		this.sellerProfile = sellerProfile;
	}

	@Column(name = "name_product", nullable = false, length = 250)
	public String getNameProduct() {
		return this.nameProduct;
	}

	public void setNameProduct(String nameProduct) {
		this.nameProduct = nameProduct;
	}

	@Column(name = "description", nullable = false, length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "price", nullable = false, precision = 12, scale = 0)
	public float getPrice() {
		return this.price;
	}

	public void setPrice(float price) {
		this.price = price;
	}

	@Column(name = "stock_quantity", nullable = false)
	public int getStockQuantity() {
		return this.stockQuantity;
	}

	public void setStockQuantity(int stockQuantity) {
		this.stockQuantity = stockQuantity;
	}

	@Column(name = "photo", nullable = false, length = 250)
	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	@Column(name = "discount_price", nullable = false, precision = 12, scale = 0)
	public float getDiscountPrice() {
		return this.discountPrice;
	}

	public void setDiscountPrice(float discountPrice) {
		this.discountPrice = discountPrice;
	}

	@Column(name = "sku", nullable = false, length = 250)
	public String getSku() {
		return this.sku;
	}

	public void setSku(String sku) {
		this.sku = sku;
	}

	@Enumerated(EnumType.STRING)
	@Column(name = "status", length = 250)
	public ProductStatus getStatus() {
		return this.status;
	}

	public void setStatus(ProductStatus status) {
		this.status = status;
	}

	@Column(name = "weight", precision = 12, scale = 0)
	public Float getWeight() {
		return this.weight;
	}

	public void setWeight(Float weight) {
		this.weight = weight;
	}

	@Column(name = "dimensions", precision = 12, scale = 0)
	public Float getDimensions() {
		return this.dimensions;
	}

	public void setDimensions(Float dimensions) {
		this.dimensions = dimensions;
	}

	@Column(name = "is_featured")
	public Boolean getIsFeatured() {
		return this.isFeatured;
	}

	public void setIsFeatured(Boolean isFeatured) {
		this.isFeatured = isFeatured;
	}

	@Column(name = "is_new")
	public Boolean getIsNew() {
		return this.isNew;
	}

	public void setIsNew(Boolean isNew) {
		this.isNew = isNew;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_at", nullable = false, length = 10)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "updated_at", nullable = false, length = 10)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<OrderItem> getOrderItems() {
		return this.orderItems;
	}

	public void setOrderItems(Set<OrderItem> orderItems) {
		this.orderItems = orderItems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<Cart> getCarts() {
		return this.carts;
	}

	public void setCarts(Set<Cart> carts) {
		this.carts = carts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<Notification> getNotifications() {
		return this.notifications;
	}

	public void setNotifications(Set<Notification> notifications) {
		this.notifications = notifications;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<ProductImages> getProductImageses() {
		return this.productImageses;
	}

	public void setProductImageses(Set<ProductImages> productImageses) {
		this.productImageses = productImageses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<PromotionProduct> getPromotionProducts() {
		return this.promotionProducts;
	}

	public void setPromotionProducts(Set<PromotionProduct> promotionProducts) {
		this.promotionProducts = promotionProducts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<ProductReview> getProductReviews() {
		return this.productReviews;
	}

	public void setProductReviews(Set<ProductReview> productReviews) {
		this.productReviews = productReviews;
	}

}
