package com.example.demo.entities;
// Generated 18:43:28, 30 thg 12, 2025 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * ProductReview generated by hbm2java
 */
@Entity
@Table(name = "product_review")
public class ProductReview implements java.io.Serializable {

	private Integer id;
	private Account account;
	private Product product;
	private int rating;
	private String commentReview;
	private Date createdAt;

	public ProductReview() {
	}

	public ProductReview(Account account, Product product, int rating, Date createdAt) {
		this.account = account;
		this.product = product;
		this.rating = rating;
		this.createdAt = createdAt;

	}

	public ProductReview(Account account, Product product, int rating, String commentReview, Date createdAt) {
		this.account = account;
		this.product = product;
		this.rating = rating;
		this.commentReview = commentReview;
		this.createdAt = createdAt;

	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "review_account_id", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "rating", nullable = false)
	public int getRating() {
		return this.rating;
	}

	public void setRating(int rating) {
		this.rating = rating;
	}

	@Column(name = "comment_review", length = 500)
	public String getCommentReview() {
		return this.commentReview;
	}

	public void setCommentReview(String commentReview) {
		this.commentReview = commentReview;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_at", nullable = false, length = 10)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

}
