package com.example.demo.entities;
// Generated 18:43:28, 30 thg 12, 2025 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.springframework.format.annotation.DateTimeFormat;

import com.example.demo.enums.DiscountTypePromotion;
import com.example.demo.enums.PromotionStatus;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Promotion generated by hbm2java
 */
@Entity
@Table(name = "promotion")
public class Promotion implements java.io.Serializable {

	private Integer id;
	private String namePromotion;
	private String description;
	private DiscountTypePromotion discountType;
	private int discountValue;
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	private Date startDate;
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	private Date endDate;
	private PromotionStatus statusPromotion;
	private int maxDiscount;
	private int minOrderValue;
	private int quantityPromotion;
	private Set<PromotionAccount> promotionAccounts = new HashSet<PromotionAccount>(0);
	private Set<Notification> notifications = new HashSet<Notification>(0);
	private Set<PromotionCategory> promotionCategories = new HashSet<PromotionCategory>(0);
	private Set<PromotionCondition> promotionConditions = new HashSet<PromotionCondition>(0);
	private Set<PromotionProduct> promotionProducts = new HashSet<PromotionProduct>(0);

	public Promotion() {
	}

	public Promotion(String namePromotion, String description, DiscountTypePromotion discountType, int discountValue,
			Date startDate, Date endDate, PromotionStatus statusPromotion, int maxDiscount, int minOrderValue,
			int quantityPromotion) {
		this.namePromotion = namePromotion;
		this.description = description;
		this.discountType = discountType;
		this.discountValue = discountValue;
		this.startDate = startDate;
		this.endDate = endDate;
		this.statusPromotion = statusPromotion;
		this.maxDiscount = maxDiscount;
		this.minOrderValue = minOrderValue;
		this.quantityPromotion = quantityPromotion;
	}

	public Promotion(String namePromotion, String description, DiscountTypePromotion discountType, int discountValue,
			Date startDate, Date endDate, PromotionStatus statusPromotion, int maxDiscount, int minOrderValue,
			int quantityPromotion, Set<PromotionAccount> promotionAccounts, Set<Notification> notifications,
			Set<PromotionCategory> promotionCategories, Set<PromotionCondition> promotionConditions,
			Set<PromotionProduct> promotionProducts) {
		this.namePromotion = namePromotion;
		this.description = description;
		this.discountType = discountType;
		this.discountValue = discountValue;
		this.startDate = startDate;
		this.endDate = endDate;
		this.statusPromotion = statusPromotion;
		this.maxDiscount = maxDiscount;
		this.minOrderValue = minOrderValue;
		this.quantityPromotion = quantityPromotion;
		this.promotionAccounts = promotionAccounts;
		this.notifications = notifications;
		this.promotionCategories = promotionCategories;
		this.promotionConditions = promotionConditions;
		this.promotionProducts = promotionProducts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name_promotion", nullable = false, length = 250)
	public String getNamePromotion() {
		return this.namePromotion;
	}

	public void setNamePromotion(String namePromotion) {
		this.namePromotion = namePromotion;
	}

	@Column(name = "description", nullable = false, length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Enumerated(EnumType.STRING)
	@Column(name = "discount_type", nullable = false, length = 250)
	public DiscountTypePromotion getDiscountType() {
		return this.discountType;
	}

	public void setDiscountType(DiscountTypePromotion discountType) {
		this.discountType = discountType;
	}

	@Column(name = "discount_value", nullable = false)
	public int getDiscountValue() {
		return this.discountValue;
	}

	public void setDiscountValue(int discountValue) {
		this.discountValue = discountValue;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "start_date", nullable = false, length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "end_date", nullable = false, length = 10)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Enumerated(EnumType.STRING)
	@Column(name = "status_promotion", nullable = false, length = 250)
	public PromotionStatus getStatusPromotion() {
		return this.statusPromotion;
	}

	public void setStatusPromotion(PromotionStatus statusPromotion) {
		this.statusPromotion = statusPromotion;
	}

	@Column(name = "max_discount", nullable = false)
	public int getMaxDiscount() {
		return this.maxDiscount;
	}

	public void setMaxDiscount(int maxDiscount) {
		this.maxDiscount = maxDiscount;
	}

	@Column(name = "min_order_value", nullable = false)
	public int getMinOrderValue() {
		return this.minOrderValue;
	}

	public void setMinOrderValue(int minOrderValue) {
		this.minOrderValue = minOrderValue;
	}

	@Column(name = "quantity_promotion", nullable = false)
	public int getQuantityPromotion() {
		return this.quantityPromotion;
	}

	public void setQuantityPromotion(int quantityPromotion) {
		this.quantityPromotion = quantityPromotion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "promotion")
	public Set<PromotionAccount> getPromotionAccounts() {
		return this.promotionAccounts;
	}

	public void setPromotionAccounts(Set<PromotionAccount> promotionAccounts) {
		this.promotionAccounts = promotionAccounts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "promotion")
	public Set<Notification> getNotifications() {
		return this.notifications;
	}

	public void setNotifications(Set<Notification> notifications) {
		this.notifications = notifications;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "promotion")
	public Set<PromotionCategory> getPromotionCategories() {
		return this.promotionCategories;
	}

	public void setPromotionCategories(Set<PromotionCategory> promotionCategories) {
		this.promotionCategories = promotionCategories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "promotion")
	public Set<PromotionCondition> getPromotionConditions() {
		return this.promotionConditions;
	}

	public void setPromotionConditions(Set<PromotionCondition> promotionConditions) {
		this.promotionConditions = promotionConditions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "promotion")
	public Set<PromotionProduct> getPromotionProducts() {
		return this.promotionProducts;
	}

	public void setPromotionProducts(Set<PromotionProduct> promotionProducts) {
		this.promotionProducts = promotionProducts;
	}

}
