package com.example.demo.entities;
// Generated 18:43:28, 30 thg 12, 2025 by Hibernate Tools 4.3.6.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;

import com.example.demo.enums.ConditionTypePromotionCondition;

import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * PromotionCondition generated by hbm2java
 */
@Entity
@Table(name = "promotion_condition")
public class PromotionCondition implements java.io.Serializable {

	private Integer id;
	private Promotion promotion;
	private ConditionTypePromotionCondition conditionType;
	private String conditionValue;

	public PromotionCondition() {
	}

	public PromotionCondition(Promotion promotion, ConditionTypePromotionCondition conditionType,
			String conditionValue) {
		this.promotion = promotion;
		this.conditionType = conditionType;
		this.conditionValue = conditionValue;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "promotion_id", nullable = false)
	public Promotion getPromotion() {
		return this.promotion;
	}

	public void setPromotion(Promotion promotion) {
		this.promotion = promotion;
	}

	@Enumerated(EnumType.STRING)
	@Column(name = "condition_type", nullable = false, length = 250)
	public ConditionTypePromotionCondition getConditionType() {
		return this.conditionType;
	}

	public void setConditionType(ConditionTypePromotionCondition conditionType) {
		this.conditionType = conditionType;
	}

	@Column(name = "condition_value", nullable = false, length = 250)
	public String getConditionValue() {
		return this.conditionValue;
	}

	public void setConditionValue(String conditionValue) {
		this.conditionValue = conditionValue;
	}

}
