package com.example.demo.entities;
// Generated 18:43:28, 30 thg 12, 2025 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.example.demo.enums.ApprovedStatus;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;

/**
 * SellerProfile generated by hbm2java
 */
@Entity
@Table(name = "seller_profile", uniqueConstraints = { @UniqueConstraint(columnNames = "business_license_number"),
		@UniqueConstraint(columnNames = "tax_code") })
public class SellerProfile implements java.io.Serializable {

	private Integer id;
	private Account account;
	private String storeName;
	private String taxCode;
	private String businessLicenseNumber;
	private String storeAddress;
	private String logo;
	private String description;
	private ApprovedStatus approvedStatus;
	private Date createdAt;
	private Date updatedAt;
	private int reviewCount;
	private float avgRating;
	private Set<Product> products = new HashSet<Product>(0);
	private Set<Product> products_1 = new HashSet<Product>(0);
	private Set<SellerReview> sellerReviews = new HashSet<SellerReview>(0);

	public SellerProfile() {
	}

	public SellerProfile(Account account, String storeName, String taxCode, String businessLicenseNumber,
			String storeAddress, String logo, String description, ApprovedStatus approvedStatus, Date createdAt, Date updatedAt,
			int reviewCount, float avgRating) {
		this.account = account;
		this.storeName = storeName;
		this.taxCode = taxCode;
		this.businessLicenseNumber = businessLicenseNumber;
		this.storeAddress = storeAddress;
		this.logo = logo;
		this.description = description;
		this.approvedStatus = approvedStatus;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.reviewCount = reviewCount;
		this.avgRating = avgRating;
	}

	public SellerProfile(Account account, String storeName, String taxCode, String businessLicenseNumber,
			String storeAddress, String logo, String description, ApprovedStatus approvedStatus, Date createdAt, Date updatedAt,
			int reviewCount, float avgRating, Set<Product> products, Set<Product> products_1,
			Set<SellerReview> sellerReviews) {
		this.account = account;
		this.storeName = storeName;
		this.taxCode = taxCode;
		this.businessLicenseNumber = businessLicenseNumber;
		this.storeAddress = storeAddress;
		this.logo = logo;
		this.description = description;
		this.approvedStatus = approvedStatus;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.reviewCount = reviewCount;
		this.avgRating = avgRating;
		this.products = products;
		this.products_1 = products_1;
		this.sellerReviews = sellerReviews;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account_id", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@Column(name = "store_name", nullable = false, length = 250)
	public String getStoreName() {
		return this.storeName;
	}

	public void setStoreName(String storeName) {
		this.storeName = storeName;
	}

	@Column(name = "tax_code", unique = true, nullable = false, length = 250)
	public String getTaxCode() {
		return this.taxCode;
	}

	public void setTaxCode(String taxCode) {
		this.taxCode = taxCode;
	}

	@Column(name = "business_license_number", unique = true, nullable = false, length = 250)
	public String getBusinessLicenseNumber() {
		return this.businessLicenseNumber;
	}

	public void setBusinessLicenseNumber(String businessLicenseNumber) {
		this.businessLicenseNumber = businessLicenseNumber;
	}

	@Column(name = "store_address", nullable = false, length = 500)
	public String getStoreAddress() {
		return this.storeAddress;
	}

	public void setStoreAddress(String storeAddress) {
		this.storeAddress = storeAddress;
	}

	@Column(name = "logo", nullable = false, length = 250)
	public String getLogo() {
		return this.logo;
	}

	public void setLogo(String logo) {
		this.logo = logo;
	}

	@Column(name = "description", nullable = false, length = 1000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Enumerated(EnumType.STRING)
	@Column(name = "approved_status", nullable = false, length = 250)
	public ApprovedStatus getApprovedStatus() {
		return this.approvedStatus;
	}

	public void setApprovedStatus(ApprovedStatus approvedStatus) {
		this.approvedStatus = approvedStatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_at", nullable = false, length = 10)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "updated_at", nullable = false, length = 10)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "review_count", nullable = false)
	public int getReviewCount() {
		return this.reviewCount;
	}

	public void setReviewCount(int reviewCount) {
		this.reviewCount = reviewCount;
	}

	@Column(name = "avg_rating", nullable = false, precision = 12, scale = 0)
	public float getAvgRating() {
		return this.avgRating;
	}

	public void setAvgRating(float avgRating) {
		this.avgRating = avgRating;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sellerProfile")
	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sellerProfile")
	public Set<Product> getProducts_1() {
		return this.products_1;
	}

	public void setProducts_1(Set<Product> products_1) {
		this.products_1 = products_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sellerProfile")
	public Set<SellerReview> getSellerReviews() {
		return this.sellerReviews;
	}

	public void setSellerReviews(Set<SellerReview> sellerReviews) {
		this.sellerReviews = sellerReviews;
	}

}
