package com.example.demo.entities;
// Generated 18:43:28, 30 thg 12, 2025 by Hibernate Tools 4.3.6.Final



import java.math.BigInteger;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;

/**
 * ShipperProfile generated by hbm2java
 */
@Entity
@Table(name = "shipper_profile", uniqueConstraints = { @UniqueConstraint(columnNames = "driving_license_number"),
		@UniqueConstraint(columnNames = "license_plate") })
public class ShipperProfile implements java.io.Serializable {

	private Integer id;
	private Account account;
	private String vehicleType;
	private String licensePlate;
	private String drivingLicenseNumber;
	private String status;
	private boolean available;
	private Date createdAt;
	private Date updatedAt;
	private int totalDeliveries;
	private BigInteger currentLatitude;
	private BigInteger currentLongitude;
	private int reviewCount;
	private float avgRating;
	private Set<ShipperReview> shipperReviews = new HashSet<ShipperReview>(0);

	public ShipperProfile() {
	}

	public ShipperProfile(Account account, String vehicleType, String licensePlate, String drivingLicenseNumber,
			String status, boolean available, Date createdAt, Date updatedAt, int totalDeliveries,
			BigInteger currentLatitude, BigInteger currentLongitude, int reviewCount, float avgRating) {
		this.account = account;
		this.vehicleType = vehicleType;
		this.licensePlate = licensePlate;
		this.drivingLicenseNumber = drivingLicenseNumber;
		this.status = status;
		this.available = available;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.totalDeliveries = totalDeliveries;
		this.currentLatitude = currentLatitude;
		this.currentLongitude = currentLongitude;
		this.reviewCount = reviewCount;
		this.avgRating = avgRating;
	}

	public ShipperProfile(Account account, String vehicleType, String licensePlate, String drivingLicenseNumber,
			String status, boolean available, Date createdAt, Date updatedAt, int totalDeliveries,
			BigInteger currentLatitude, BigInteger currentLongitude, int reviewCount, float avgRating,
			Set<ShipperReview> shipperReviews) {
		this.account = account;
		this.vehicleType = vehicleType;
		this.licensePlate = licensePlate;
		this.drivingLicenseNumber = drivingLicenseNumber;
		this.status = status;
		this.available = available;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.totalDeliveries = totalDeliveries;
		this.currentLatitude = currentLatitude;
		this.currentLongitude = currentLongitude;
		this.reviewCount = reviewCount;
		this.avgRating = avgRating;
		this.shipperReviews = shipperReviews;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account_id", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@Column(name = "vehicle_type", nullable = false, length = 250)
	public String getVehicleType() {
		return this.vehicleType;
	}

	public void setVehicleType(String vehicleType) {
		this.vehicleType = vehicleType;
	}

	@Column(name = "license_plate", unique = true, nullable = false, length = 250)
	public String getLicensePlate() {
		return this.licensePlate;
	}

	public void setLicensePlate(String licensePlate) {
		this.licensePlate = licensePlate;
	}

	@Column(name = "driving_license_number", unique = true, nullable = false, length = 250)
	public String getDrivingLicenseNumber() {
		return this.drivingLicenseNumber;
	}

	public void setDrivingLicenseNumber(String drivingLicenseNumber) {
		this.drivingLicenseNumber = drivingLicenseNumber;
	}

	@Column(name = "status", nullable = false, length = 250)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "available", nullable = false)
	public boolean isAvailable() {
		return this.available;
	}

	public void setAvailable(boolean available) {
		this.available = available;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_at", nullable = false, length = 10)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "updated_at", nullable = false, length = 10)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "total_deliveries", nullable = false)
	public int getTotalDeliveries() {
		return this.totalDeliveries;
	}

	public void setTotalDeliveries(int totalDeliveries) {
		this.totalDeliveries = totalDeliveries;
	}

	@Column(name = "current_latitude", nullable = false, precision = 20, scale = 0)
	public BigInteger getCurrentLatitude() {
		return this.currentLatitude;
	}

	public void setCurrentLatitude(BigInteger currentLatitude) {
		this.currentLatitude = currentLatitude;
	}

	@Column(name = "current_longitude", nullable = false, precision = 20, scale = 0)
	public BigInteger getCurrentLongitude() {
		return this.currentLongitude;
	}

	public void setCurrentLongitude(BigInteger currentLongitude) {
		this.currentLongitude = currentLongitude;
	}

	@Column(name = "review_count", nullable = false)
	public int getReviewCount() {
		return this.reviewCount;
	}

	public void setReviewCount(int reviewCount) {
		this.reviewCount = reviewCount;
	}

	@Column(name = "avg_rating", nullable = false, precision = 12, scale = 0)
	public float getAvgRating() {
		return this.avgRating;
	}

	public void setAvgRating(float avgRating) {
		this.avgRating = avgRating;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "shipperProfile")
	public Set<ShipperReview> getShipperReviews() {
		return this.shipperReviews;
	}

	public void setShipperReviews(Set<ShipperReview> shipperReviews) {
		this.shipperReviews = shipperReviews;
	}

}
